### ISSUE TITLE
Could not convert keep to numeical file mode

### ISSUE THREAD

**Issue by pfr-dev** [edneville/please#3]
I manually bootstrapped your [commit](https://github.com/void-linux/void-packages/pull/31430/commits/c562957f5e51f4a51c92c8bc04327f35643b84a3) to void-packages and it compiled and installed successfuly. 

**INFO:**

**User:** `dave`
**Hostname:** `void`

`/etc/please.ini`:
```
[dave_root_require_pass]
name = dave
target = root
hostname = void
regex = .*

[dave_edit]
name = dave
require_pass = true
type = edit
editmode = keep
regex = ^.*$

[dave_root_no_pass_reboot]
name = dave
require_pass = false
hostname = void
regex = /sbin/reboot
```

`/etc/pam.d/please`:
```
#%PAM-1.0
auth   include  system-auth
account  include  system-auth
session  include  system-auth
```

`/etc/pam.d/pleaseedit`:
```
#%PAM-1.0
auth   include  system-auth
account  include  system-auth
session  include  system-auth
```

**Output:**
```
$ ~ pleaseedit /etc/please.ini
Could not convert keep to numerical file mode
Exiting due to error, cannot fully process /etc/please.ini
```

**Comment by edneville** [comment]
@pfr-dev, thanks for your interest.

editmode = keep was introduced in 0.5.0, which that commit didn't reference.

If you change the template to use version 0.5.0, you should be able to rebuild the package.

```
--- a/srcpkgs/pleaser/template
+++ b/srcpkgs/pleaser/template
@@ -1,7 +1,7 @@
 # Template file for 'pleaser'
 pkgname=pleaser
 _binary=please
-version=0.4.1
+version=0.5.0
 revision=1
 wrksrc="${_binary}-v${version}"
 build_style=cargo
@@ -11,7 +11,7 @@ maintainer="Ed Neville <ed@s5h.net>"
 license="GPL-3.0-or-later"
 homepage="https://www.usenix.org.uk/content/please.html"
 distfiles="https://gitlab.com/edneville/${_binary}/-/archive/v${version}/${_binary}-v${version}.tar.gz"
-checksum=0c81449d57a6bbbf1577d6474349f845e9a8c7a074b27fd1a4ef119ccd4f3c64
+checksum=2bee467f599aaab9fd67f7ca0438118ce4b82c7a8925d87cf35efcdef1621bcf

 pre_build() {
  export CFLAGS_${RUST_BUILD//-/_}="${CFLAGS_host}"
```

0.5.1 will soon have editmode=keep as the default.

**Comment by pfr-dev** [comment]
Excellent, I will try that. 

> 0.5.1 will soon have editmode=keep as the default.

I noticed that the package wasn't accepted into Void repo's. How can I update to 0.5.1 in the future?

**Comment by edneville** [comment]
Without it in their repo I don't think there's any form of automatic update. What I can do is try and keep the master branch updated at https://github.com/edneville/void-packages. I'll see if I can find out what the blockers were.

**Comment by pfr-dev** [comment]
> What I can do is try and keep the master branch updated

That works for me. I've just subscribed to get notified of new releases and I'm happy to update manually for now. It is a bit frustrating the way Void wont accept new packages becuase they replicate/duplicate a service or function of another package. Anyway, good luck with it and thanks for your work :)

**Comment by pfr-dev** [comment]
Quick question:

its working now on 0.5.0 but I'm getting this output everytime. Any idea how to fix this?
```
Could not connect to syslog: Error(Initialization, State { next_error: Some(Error(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), State { next_error: None, backtrace: InternalBacktrace })), backtrace: InternalBacktrace })
```

**Comment by edneville** [comment]
That is please saying that it cannot log the action, which is the default behaviour. If you don't have syslog installed adding:

```
syslog=false
```

To the matching entry will stop this. The error message isn't very aesthetic, "Could not connect to syslog" alone may be better.

**Comment by pfr-dev** [comment]
Thank you! Closing this now. 

Just curious thought, I can't find `syslog` in void-packages. Is `rsyslog` the package that should solve this also?

**Comment by edneville** [comment]
@pfr-dev, no problem, rsyslog or socklog-void will receive messages from please, depending on what your preference is.
